/*SQL STATEMENTS FOR OUR FINAL DATABASE PROJECT*/
-------------
--JUST DATE--
-------------
--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR AFTER A SPCIFIC DATE--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date > {0};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR BEFORE A SPCIFIC DATE--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date < {0};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR ON A SPCIFIC DATE--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date = {0};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR FROM {0} to {1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date >= {0} AND C.DATE <= {1};

-----------------
--DATE AND TIME--
-----------------
--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR AFTER A SPCIFIC DATE{0} AFTER A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date > {0} AND S.TIME > {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR BEFORE A SPCIFIC DATE{0} AFTER A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date < {0} AND S.Time > {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR ON A SPCIFIC DATE{0} AFTER A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date = {0} AND S.Time > {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR FROM {0} to {1} AFTER A SPECIFIC TIME {2}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date >= {0} AND C.DATE <= {1} AND S.Time > {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR AFTER A SPCIFIC DATE{0} BEFORE A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date > {0} AND S.TIME < {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR BEFORE A SPCIFIC DATE{0} BEFORE A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date < {0} AND S.Time < {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR ON A SPCIFIC DATE{0} BEFORE A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date = {0} AND S.Time < {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR FROM {0} to {1} BEFORE A SPECIFIC TIME {2}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date >= {0} AND C.DATE <= {1} AND S.Time < {2};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR AFTER A SPCIFIC DATE{0} AT A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date > {0} AND S.TIME = {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR BEFORE A SPCIFIC DATE{0} AT A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date < {0} AND S.Time = {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR ON A SPCIFIC DATE{0} AT A SPECIFIC TIME{1}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date = {0} AND S.Time = {1};

--PULLS MOVIE INFO AND TIME(CAN INCLUDE THEATER IN LATER QUERY) FOR FROM {0} to {1} AT A SPECIFIC TIME {2}--
SELECT *
FROM Schedule S LEFT OUTER JOIN Calendar C ON S.ScheduleID = C.Calendar ID LEFT OUT JOIN Movie M ON S.movie_id = M.movie_id
WHERE C.Date >= {0} AND C.DATE <= {1} AND S.Time = {2};

----------------------
--BOX OFFICE QUERIES--
----------------------
--PRICE OF A KID--
SELECT BO.price_kid
FROM BoxOffice BO;

--PRICE OF ADULT--
SELECT BO.price_adult
FROM BoxOffice BO;

--PRICE OF MATINEE--
SELECT BO.price_matinee
FROM BoxOffice BO;

--PRICE OF DISCOUNTED--
Select BO.price_senior_student
FROM BoxOffice BO;

